// Quiz asset identifiers, NOT the figure numbering of DPR 495/1992.
// Italian identities cross-checked against the published AB list (27/02/2025).
// See docs/figure-details.md for provenance and the review/update contract.
const rows = [
  [1, 'Strada deformata', 'অসমতল রাস্তা', 17],
  [2, 'Dosso', 'রাস্তার উঁচু অংশ', 18],
  [3, 'Cunetta', 'রাস্তার নিচু অংশ', 19],
  [4, 'Curva pericolosa a destra', 'ডান দিকে বিপজ্জনক বাঁক', 20],
  [5, 'Curva pericolosa a sinistra', 'বাম দিকে বিপজ্জনক বাঁক', 21],
  [8, 'Passaggio a livello con barriere o semibarriere', 'বাধাযুক্ত রেলক্রসিং', 24],
  [9, 'Passaggio a livello senza barriere', 'বাধাবিহীন রেলক্রসিং', 25],
  [10, 'Croce di Sant’Andrea', 'এক লাইনের রেলক্রসিংয়ের ক্রস চিহ্ন', 26],
  [11, 'Doppia croce di Sant’Andrea', 'একাধিক লাইনের রেলক্রসিংয়ের দ্বৈত ক্রস চিহ্ন', 26],
  [13, 'Pannelli distanziometrici dei passaggi a livello', 'রেলক্রসিংয়ের দূরত্ব নির্দেশক প্যানেল', 27],
  [14, 'Attraversamento tranviario', 'ট্রাম চলাচলের পথ অতিক্রম', 27],
  [15, 'Pericolo: attraversamento pedonale', 'সামনে পথচারী পারাপার', 28],
  [16, 'Pericolo: attraversamento ciclabile', 'সামনে সাইকেল পারাপার', 29],
  [17, 'Discesa pericolosa', 'বিপজ্জনক নিচের ঢাল', 30],
  [18, 'Salita ripida', 'খাড়া উপরের ঢাল', 31],
  [22, 'Ponte mobile', 'খোলা ও বন্ধ করা যায় এমন সেতু', 34],
  [23, 'Banchina cedevole', 'রাস্তার দুর্বল পাশের অংশ', 35],
  [24, 'Strada sdrucciolevole', 'পিচ্ছিল রাস্তা', 35],
  [28, 'Doppio senso di circolazione', 'দুই দিকে যান চলাচল', 37],
  [30, 'Sbocco su molo o argine', 'রাস্তা ঘাট বা নদীর পাড়ে গিয়ে শেষ', 38],
  [31, 'Materiale instabile sulla strada', 'রাস্তায় আলগা পাথর বা কাঁকর', 39],
  [34, 'Preavviso di semaforo verticale', 'সামনে উল্লম্ব ট্রাফিক সিগন্যাল', 40],
  [37, 'Forte vento laterale', 'পাশ থেকে প্রবল বাতাস', 42],
  [38, 'Pericolo di incendio', 'আগুন লাগার বিপদ', 43],
  [40, 'Dare precedenza', 'অগ্রাধিকার দিতে হবে', 44],
  [41, 'Fermarsi e dare precedenza (STOP)', 'থামুন এবং অগ্রাধিকার দিন', 45],
  [42, 'Preavviso di dare precedenza', 'সামনে অগ্রাধিকার দেওয়ার সংকেত', 45],
  [43, 'Preavviso di fermarsi e dare precedenza', 'সামনে থেমে অগ্রাধিকার দেওয়ার সংকেত', 46],
  [44, 'Intersezione con precedenza a destra', 'মোড়ে ডান দিকের যানকে অগ্রাধিকার', 46],
  [45, 'Dare precedenza nei sensi unici alternati', 'পর্যায়ক্রমিক একমুখী পথে বিপরীত যানকে অগ্রাধিকার দিন', 51],
  [46, 'Fine del diritto di precedenza', 'অগ্রাধিকারের রাস্তা শেষ', 50],
  [47, 'Intersezione con diritto di precedenza', 'মোড়ে আপনার অগ্রাধিকার আছে', 47],
  [50, 'Confluenza a destra', 'ডান দিক থেকে রাস্তা এসে মিশছে', 48],
  [51, 'Confluenza a sinistra', 'বাম দিক থেকে রাস্তা এসে মিশছে', 49],
  [52, 'Diritto di precedenza', 'অগ্রাধিকারের রাস্তা', 49],
  [53, 'Diritto di precedenza nei sensi unici alternati', 'পর্যায়ক্রমিক একমুখী পথে আপনার অগ্রাধিকার', 52],
  [54, 'Divieto di transito', 'যান চলাচল নিষিদ্ধ', 53],
  [55, 'Senso vietato', 'এই দিক থেকে প্রবেশ নিষিদ্ধ', 54],
  [56, 'Divieto di sorpasso', 'ওভারটেক করা নিষিদ্ধ', 55],
  [57, 'Distanziamento minimo obbligatorio', 'ন্যূনতম দূরত্ব বজায় রাখা বাধ্যতামূলক', 54],
  [59, 'Divieto di segnalazioni acustiche', 'হর্ন বাজানো নিষিদ্ধ', 55],
  [60, 'Divieto di sorpasso per veicoli merci oltre 3,5 t', '৩.৫ টনের বেশি পণ্যবাহী যানের ওভারটেক নিষিদ্ধ', 58],
  [63, 'Transito vietato alle biciclette', 'সাইকেল চলাচল নিষিদ্ধ', 62],
  [64, 'Transito vietato ai motocicli', 'মোটরসাইকেল চলাচল নিষিদ্ধ', 62],
  [66, 'Transito vietato a tutti gli autoveicoli', 'তিন বা তার বেশি চাকার মোটরযান চলাচল নিষিদ্ধ', 63],
  [67, 'Transito vietato agli autobus', 'বাস চলাচল নিষিদ্ধ', 64],
  [68, 'Transito vietato ai veicoli merci oltre 3,5 t', '৩.৫ টনের বেশি পণ্যবাহী যান চলাচল নিষিদ্ধ', 65],
  [70, 'Transito vietato ai veicoli a motore trainanti un rimorchio', 'ট্রেলার টানা মোটরযান চলাচল নিষিদ্ধ', 66],
  [71, 'Transito vietato alle macchine agricole', 'কৃষিযন্ত্র চলাচল নিষিদ্ধ', 63],
  [72, 'Transito vietato ai veicoli che trasportano merci pericolose', 'বিপজ্জনক পণ্যবাহী যান চলাচল নিষিদ্ধ', 66],
  [73, 'Transito vietato ai veicoli che trasportano esplosivi o prodotti infiammabili', 'বিস্ফোরক বা দাহ্য পণ্যবাহী যান চলাচল নিষিদ্ধ', 67],
  [75, 'Larghezza massima: 2,30 m', 'সর্বোচ্চ প্রস্থ: ২.৩০ মিটার', 67],
  [76, 'Altezza massima: 3,50 m', 'সর্বোচ্চ উচ্চতা: ৩.৫০ মিটার', 68],
  [77, 'Lunghezza massima: 10 m', 'সর্বোচ্চ দৈর্ঘ্য: ১০ মিটার', 68],
  [78, 'Massa massima: 7 t', 'সর্বোচ্চ মোট ওজন: ৭ টন', 69],
  [79, 'Massa massima per asse: 2,5 t', 'প্রতি অক্ষে সর্বোচ্চ ওজন: ২.৫ টন', 69],
  [80, 'Via libera', 'আগের স্থানীয় নিষেধাজ্ঞাগুলোর সমাপ্তি', 70],
  [81, 'Fine del limite massimo di velocità', 'সর্বোচ্চ গতিসীমার সমাপ্তি', 60],
  [82, 'Fine del divieto di sorpasso', 'ওভারটেক নিষেধাজ্ঞার সমাপ্তি', 57],
  [83, 'Fine del divieto di sorpasso per veicoli merci oltre 3,5 t', '৩.৫ টনের বেশি পণ্যবাহী যানের ওভারটেক নিষেধাজ্ঞা শেষ', 57],
  [84, 'Divieto di sosta', 'পার্কিং নিষিদ্ধ', 70],
  [85, 'Divieto di fermata', 'থামা নিষিদ্ধ', 74],
  [86, 'Parcheggio', 'পার্কিংয়ের স্থান', 75],
  [90, 'Passo carrabile', 'যানবাহন প্রবেশ ও বের হওয়ার পথ', 73],
  [91, 'Sosta riservata alle persone con disabilità', 'প্রতিবন্ধী ব্যক্তিদের জন্য সংরক্ষিত পার্কিং', 72],
  [92, 'Regolazione flessibile della sosta', 'সময় অনুযায়ী পার্কিংয়ের নিয়ম', 72],
  [96, 'Preavviso di direzione obbligatoria a destra', 'সামনে ডান দিকে যাওয়া বাধ্যতামূলক', 79],
  [98, 'Direzioni consentite: destra e sinistra', 'ডান অথবা বাম দিকে যেতে হবে', 81],
  [101, 'Passaggio obbligatorio a sinistra', 'বাধার বাম দিক দিয়ে যেতে হবে', 84],
  [102, 'Passaggio obbligatorio a destra', 'বাধার ডান দিক দিয়ে যেতে হবে', 85],
  [103, 'Passaggi consentiti: destra e sinistra', 'বাধার ডান বা বাম দিক দিয়ে যাওয়া যায়', 86],
  [104, 'Rotatoria', 'গোলচত্বর', 87],
  [105, 'Limite minimo di velocità', 'ন্যূনতম গতিসীমা', 88],
  [106, 'Fine del limite minimo di velocità', 'ন্যূনতম গতিসীমার সমাপ্তি', 89],
  [107, 'Catene da neve obbligatorie', 'তুষারের চেইন ব্যবহার বাধ্যতামূলক', 89],
  [108, 'Percorso pedonale', 'পথচারীদের জন্য নির্ধারিত পথ', 90],
  [112, 'Pista ciclabile contigua al marciapiede', 'ফুটপাতের পাশের আলাদা সাইকেলপথ', 92],
  [113, 'Percorso pedonale e ciclabile', 'পথচারী ও সাইকেলের যৌথ পথ', 93],
  [115, 'Fine del percorso pedonale e ciclabile', 'পথচারী ও সাইকেলের যৌথ পথ শেষ', 93],
  [117, 'Fine del percorso per animali da soma e da sella', 'বোঝাবাহী ও চড়ার পশুর নির্ধারিত পথ শেষ', 94],
  [118, 'Alt — Dogana', 'থামুন — শুল্ক পরীক্ষা', 96],
  [119, 'Alt — Polizia', 'থামুন — পুলিশ চেকপোস্ট', 95],
  [120, 'Alt — Stazione', 'থামুন — টোল আদায়ের স্থান', 95],
  [121, 'Pannello integrativo: distanza', 'অতিরিক্ত প্যানেল: কত দূরে', 138],
  [122, 'Pannello integrativo: estesa', 'অতিরিক্ত প্যানেল: কত দূর পর্যন্ত', 138],
  [125, 'Pannello integrativo: giorni lavorativi', 'অতিরিক্ত প্যানেল: কর্মদিবসের সময়', 140],
  [126, 'Pannello integrativo: limitazione', 'অতিরিক্ত প্যানেল: যেসব যানের জন্য প্রযোজ্য', 140],
  [138, 'Strada sdrucciolevole per ghiaccio', 'বরফের কারণে পিচ্ছিল রাস্তা', 147],
  [139, 'Strada sdrucciolevole per pioggia', 'বৃষ্টির কারণে পিচ্ছিল রাস্তা', 147],
  [150, 'Preavviso di percorso obbligatorio per autocarri', 'সামনে ট্রাকের জন্য বাধ্যতামূলক পথ', 80],
  [151, 'Divieto di transito per le categorie indicate', 'দেখানো শ্রেণির যান চলাচল নিষিদ্ধ', 53],
  [153, 'Senso unico frontale', 'সামনের দিকে একমুখী চলাচল', 115],
  [154, 'Semaforo veicolare', 'যানবাহনের ট্রাফিক সিগন্যাল', 151],
  [155, 'Semafori veicolari di corsia', 'লেনভিত্তিক ট্রাফিক সিগন্যাল', 153],
  [159, 'Semafori per corsie reversibili', 'দিক পরিবর্তনশীল লেনের সিগন্যাল', 157],
  [160, 'Luci gialle lampeggianti', 'হলুদ ঝলকানি বাতি', 158],
  [161, 'Semafori di onda verde', 'ধারাবাহিক সবুজ সিগন্যালের গতিনির্দেশ', 160],
  [162, 'Luci rosse lampeggianti', 'লাল ঝলকানি বাতি', 159],
  [166, 'Preavviso di incrocio urbano', 'সামনে শহরের রাস্তার মোড়', 98],
  [167, 'Preavviso di incroci ravvicinati urbani', 'সামনে কাছাকাছি একাধিক শহুরে মোড়', 98],
  [168, 'Preavviso di incrocio con rotatoria', 'সামনে গোলচত্বরযুক্ত মোড়', 99],
  [172, 'Preselezione urbana', 'শহরের রাস্তায় আগেই সঠিক লেন বেছে নিন', 102],
  [182, 'Itinerario extraurbano', 'শহরের বাইরের পথনির্দেশ', 105],
  [183, 'Fine del centro abitato', 'বসতিপূর্ণ এলাকার সমাপ্তি', 106],
  [184, 'Conferma autostradale', 'মোটরওয়ের গন্তব্য ও দূরত্বের নিশ্চয়তা', 105],
  [186, 'Area pedonale', 'পথচারীদের এলাকা', 117],
  [189, 'Transitabilità della strada', 'রাস্তায় চলাচলের অবস্থা', 118],
  [193, 'Transitabilità della strada', 'রাস্তায় চলাচলের অবস্থা', 119],
  [194, 'Inizio di strada extraurbana principale', 'প্রধান শহরবহির্ভূত রাস্তার শুরু', 119],
  [197, 'Limiti massimi generali di velocità', 'সাধারণ সর্বোচ্চ গতিসীমা', 191],
  [199, 'Itinerario internazionale', 'আন্তর্জাতিক সড়কপথ', 102],
  [200, 'Identificazione di autostrada', 'মোটরওয়ের পরিচয় ও নম্বর', 103],
  [201, 'Identificazione di strada statale', 'রাষ্ট্রীয় সড়কের পরিচয় ও নম্বর', 103],
  [203, 'Identificazione di strada comunale', 'পৌরসভার রাস্তার পরিচয়', 104],
  [206, 'Progressiva distanziometrica autostradale', 'মোটরওয়ের কিলোমিটার নির্দেশক', 104],
  [218, 'Attraversamento pedonale', 'পথচারী পারাপার', 109],
  [219, 'Scuolabus', 'স্কুলবাস', 110],
  [225, 'Preavviso di strada senza uscita', 'সামনে বের হওয়ার পথ নেই', 111],
  [226, 'Velocità consigliata', 'প্রস্তাবিত গতি', 112],
  [228, 'Strada riservata ai veicoli a motore', 'শুধু মোটরযানের জন্য নির্ধারিত রাস্তা', 112],
  [230, 'Galleria', 'সুড়ঙ্গ', 113],
  [231, 'Ponte', 'সেতু', 114],
  [236, 'Attraversamento ciclabile', 'সাইকেল পারাপার', 109],
  [238, 'Svolta a sinistra indiretta', 'পরোক্ষভাবে বাম দিকে মোড় নেওয়ার পথ', 114],
  [239, 'Inversione di marcia', 'বিপরীত দিকে ঘোরার স্থান', 115],
  [240, 'Piazzola di sosta', 'রাস্তার পাশে থামার নির্ধারিত স্থান', 117],
  [242, 'Uso delle corsie extraurbane', 'শহরের বাইরের রাস্তায় লেন ব্যবহারের নিয়ম', 120],
  [243, 'Velocità minime obbligatorie per corsia', 'প্রতিটি লেনের বাধ্যতামূলক ন্যূনতম গতি', 120],
  [250, 'Preavviso di deviazione per autocarri', 'সামনে ট্রাকের জন্য বিকল্প পথ', 116],
  [251, 'Direzione consigliata agli autocarri', 'ট্রাকের জন্য প্রস্তাবিত দিক', 130],
  [256, 'Fermata autobus extraurbana', 'শহরের বাইরের বাসস্টপ', 124],
  [270, 'Auto al seguito', 'ট্রেনে গাড়ি পরিবহনের ব্যবস্থা', 125],
  [273, 'Area attrezzata con impianti di scarico', 'ক্যাম্পারের বর্জ্য খালাসের সুবিধাযুক্ত স্থান', 126],
  [278, 'Cono stradale', 'রাস্তার কোণাকৃতি নিরাপত্তা চিহ্ন', 133],
  [279, 'Passaggio obbligatorio per veicoli operativi', 'কর্মরত যানের পাশ দিয়ে নির্ধারিত দিকে যেতে হবে', 132],
  [282, 'Limitazione di transito per cantiere stradale', 'রাস্তার কাজের কারণে চলাচলে সীমাবদ্ধতা', 129],
  [283, 'Preavviso di deviazione', 'সামনে বিকল্প পথে যাওয়ার নির্দেশ', 129],
  [289, 'Delineatori di margine su strade a senso unico', 'একমুখী রাস্তার কিনারা নির্দেশক', 134],
  [291, 'Delineatori di margine per gallerie', 'সুড়ঙ্গের কিনারা নির্দেশক', 135],
  [297, 'Preavviso di semaforo per lavori stradali', 'রাস্তার কাজের সামনে ট্রাফিক সিগন্যাল', 128],
  [301, 'Contrassegni posteriori dei limiti di velocità', 'যানের পেছনে লাগানো গতিসীমার চিহ্ন', 195],
  [302, 'Pannello per carichi sporgenti', 'পেছনে বেরিয়ে থাকা মাল বোঝানোর প্যানেল', 261],
  [303, 'Pannello per trasporto di merci pericolose', 'বিপজ্জনক পণ্য পরিবহনের কমলা প্যানেল', 261],
  [304, 'Pannelli posteriori per autocarri oltre 3,5 t', '৩.৫ টনের বেশি ট্রাকের পেছনের প্রতিফলক প্যানেল', 261],
  [305, 'Pannelli posteriori per rimorchi e semirimorchi', 'ট্রেলার ও সেমিট্রেলারের পেছনের প্রতিফলক প্যানেল', 261],
  [385, 'Vigile con un braccio alzato', 'ট্রাফিক পুলিশের এক হাত ওপরে', 163],
  [386, 'Vigile con le braccia ad angolo retto', 'ট্রাফিক পুলিশের দুই হাত সমকোণে', 163],
  [501, 'Striscia bianca continua di mezzeria', 'রাস্তার মাঝের একটানা সাদা রেখা', 165],
  [502, 'Striscia bianca discontinua di mezzeria', 'রাস্তার মাঝের বিচ্ছিন্ন সাদা রেখা', 166],
  [505, 'Striscia laterale discontinua presso un passo carrabile', 'যান প্রবেশপথের পাশে বিচ্ছিন্ন সাদা রেখা', 170],
  [513, 'Striscia laterale discontinua presso una piazzola di sosta', 'থামার স্থানের পাশে বিচ্ছিন্ন সাদা রেখা', 170],
  [531, 'Segnaletica orizzontale di passaggio a livello', 'রেলক্রসিংয়ের রাস্তার ওপর আঁকা চিহ্ন', 177],
  [535, 'Rallentatore di velocità', 'গতি কমানোর উঁচু বাধা', 179],
  [543, 'Strisce di guida negli incroci', 'মোড়ে পথ দেখানো সাদা রেখা', 172],
  [546, 'Segnaletica di fermata autobus', 'বাসস্টপের রাস্তার ওপর আঁকা চিহ্ন', 177],
  [547, 'Frecce direzionali', 'দিক নির্দেশক তীরচিহ্ন', 175],
  [550, 'Carreggiata a doppio senso: uso delle corsie', 'দ্বিমুখী রাস্তায় লেন ব্যবহার', 201],
  [552, 'Carreggiata a sei corsie, tre per senso di marcia', 'প্রতি দিকে তিনটি করে মোট ছয় লেনের রাস্তা', 202],
  [554, 'Schema di carreggiata: uso delle corsie', 'রাস্তার চিত্র: লেন ব্যবহার', 203],
  [559, 'Schema stradale: uso delle carreggiate', 'রাস্তার চিত্র: চলাচলের অংশ ব্যবহার', 203],
  [562, 'Strada a tre carreggiate', 'তিনটি পৃথক চলাচলের অংশযুক্ত রাস্তা', 202],
  [563, 'Striscia di arresto', 'থামার রেখা', 173],
  [566, 'Striscia discontinua affiancata a una continua', 'বিচ্ছিন্ন রেখার পাশে একটানা সাদা রেখা', 169],
  [567, 'Striscia continua affiancata a una discontinua', 'একটানা রেখার পাশে বিচ্ছিন্ন সাদা রেখা', 169],
  [574, 'Corsie di preselezione', 'মোড়ের আগে দিক অনুযায়ী বেছে নেওয়ার লেন', 176],
  [599, 'Svolta a sinistra su strada a doppio senso', 'দ্বিমুখী রাস্তায় বাম দিকে মোড় নেওয়া', 206],
  [617, 'Schema di precedenza all’incrocio', 'মোড়ে অগ্রাধিকারের চিত্র', 216],
  [638, 'Schema di precedenza all’incrocio', 'মোড়ে অগ্রাধিকারের চিত্র', 221],
  [642, 'Schema di precedenza all’incrocio', 'মোড়ে অগ্রাধিকারের চিত্র', 223],
  [667, 'Schema di precedenza all’incrocio', 'মোড়ে অগ্রাধিকারের চিত্র', 234],
  [669, 'Schema di precedenza all’incrocio', 'মোড়ে অগ্রাধিকারের চিত্র', 235],
  [670, 'Segnalazione di divieto di sosta: strisce gialle e nere', 'হলুদ ও কালো দাগ: পার্কিং নিষিদ্ধ', 178],
  [698, 'Comando della segnalazione luminosa di pericolo', 'জরুরি অবস্থার চারটি ইন্ডিকেটর জ্বালানোর সুইচ', 336],
  [704, 'Spia della temperatura del liquido di raffreddamento', 'ইঞ্জিনের কুল্যান্টের তাপমাত্রার সতর্কবাতি', 333],
  [706, 'Spia della pressione dell’olio', 'ইঞ্জিন তেলের চাপের সতর্কবাতি', 334],
  [901, 'Strada deformata con pannello di estesa', 'অসমতল রাস্তা কত দূর পর্যন্ত তার প্যানেল', 17],
  [902, 'Strada deformata con pannello di distanza', 'অসমতল রাস্তা কত দূরে তার প্যানেল', 17],
  [909, 'Doppia croce di Sant’Andrea in verticale', 'উল্লম্ব দ্বৈত ক্রস: একাধিক রেললাইন', 26],
  [910, 'Passaggio a livello con pannelli distanziometrici', 'দূরত্ব নির্দেশক প্যানেলসহ রেলক্রসিং', 27],
  [915, 'Segnale con pannello integrativo di fine', 'নির্দেশের সমাপ্তি বোঝানো প্যানেলসহ সংকেত', 142],
  [920, 'Altri pericoli con pannello integrativo', 'অতিরিক্ত প্যানেলসহ অন্যান্য বিপদের সংকেত', 43],
  [942, 'Divieto di sosta con rimozione coatta', 'পার্কিং নিষিদ্ধ — গাড়ি সরিয়ে নেওয়া হবে', 148],
  [945, 'Divieto di sosta con orario dei giorni lavorativi', 'কর্মদিবসের নির্দিষ্ট সময়ে পার্কিং নিষিদ্ধ', 140],
  [949, 'Divieto di sosta con pannello integrativo', 'অতিরিক্ত প্যানেলসহ পার্কিং নিষেধাজ্ঞা', 71],
  [955, 'Divieto di fermata con pannello integrativo', 'অতিরিক্ত প্যানেলসহ থামা নিষেধাজ্ঞা', 74],
  [957, 'Divieto di fermata: fine', 'থামা নিষেধাজ্ঞার সমাপ্তি', 142]
];

export const FIGURE_CATALOG_SOURCE = 'https://www.neca.it/assets/pdf/ListatoAB.pdf';
export const FIGURE_CATALOG = Object.freeze(Object.fromEntries(rows.map(([number, italian, bangla, page]) => [
  `fig${number}`, Object.freeze({ id: `fig${number}`, number, italian, bangla, page })
])));

export function normalizeFigureId(value) {
  const clean = String(value ?? '').normalize('NFKC').trim().split(/[?#]/, 1)[0].replace(/\\/g, '/');
  const match = clean.split('/').pop().match(/^(?:fig[\s_-]*)?0*(\d+)(?:\.[a-z0-9]+)?$/i);
  const number = match && Number(match[1]);
  return Number.isSafeInteger(number) && number > 0 ? `fig${number}` : '';
}

export function getFigureDetail(value) {
  return FIGURE_CATALOG[normalizeFigureId(value)] || null;
}
